### ISSUE TITLE
Find true braids

### ISSUE THREAD

**Issue by jesselangdon** [SouthForkResearch/pyGNAT#11]
We need to be able to automatically label stream features as "true" braids, vs stream features that form a polygon (for instance, when canals cross a two or more stream channels.)

**Comment by MattReimer** [comment]
I think we might be able to do this with [NetowrkX and cycles](https://networkx.github.io/documentation/networkx-1.10/reference/algorithms.cycles.html):

from [wikipedia](https://en.wikipedia.org/wiki/Cycle_graph):

> In graph theory, a cycle graph or circular graph is a graph that consists of a single cycle, or in other words, some number of vertices connected in a closed chain. The cycle graph with n vertices is called Cn.

**The way I would approach this problem**:

1. Parse the SHP file into a simplified networkX object
2. Find all the cycles
3. Loop over each cycle and determine the "trueness" of the braid. 
4. Output the results (possibly to a shapefile using shapely)

**Comment by MattReimer** [comment]
Check out the commit above. It demonstrates (I think) how we can identift braids:

The output is:

![screen shot 2017-03-10 at 12 10 23 pm](https://cloud.githubusercontent.com/assets/1063391/23811381/969e5156-058a-11e7-86a4-9c35a75f8e84.png)

**Comment by jesselangdon** [comment]
We also be need to be able to filter out stream segments by attributes.
bd6bb3cc792e3086427820e37a69008635f84af3

**Comment by jesselangdon** [comment]
This has been incorporated into network.py
