### ISSUE TITLE
QGIS plugin forms

### ISSUE THREAD

**Issue by jesselangdon** [SouthForkResearch/pyGNAT#19]
Here are a couple of form mockups for the first couple of processing steps in the QGIS plugin.

[Build Network Tool form](https://github.com/SouthForkResearch/pyGNAT/blob/master/assets/Build%20Networks%20Tool%20Form.png)
[Calculate Network Metrics form](https://github.com/SouthForkResearch/pyGNAT/blob/master/assets/Calculate%20Network%20Metrics.png)

Please review and let me know what you think.

**Comment by MattReimer** [comment]
Sorry to be late on this one. I think the forms look good. Obviously when you code them things will get tweaked based on what Qt forms can and can't do but I think the general idea is good.
