### ISSUE TITLE
Identify incorrect flow direction

### ISSUE THREAD

**Issue by jesselangdon** [SouthForkResearch/pyGNAT#3]
Each stream reach show know which adjacent reaches are upstream.

Required for:
- accurate segmentation (and accurate catchment delineation)
- determine accurate routes
- identify all upstream reaches from a selected point

**Comment by MattReimer** [comment]
This one sounds kind of fun. 

We discussed directed graphs other issues like: https://github.com/SouthForkResearch/pyGNAT/issues/7

I think all we have to do here is the same kind of thing and then compare adjacent nodes to see if there's a problem then flag all the problems.

**Comment by jesselangdon** [comment]
I found an interesting tool built for shapefile networks called [nx_spatial](https://bitbucket.org/gallipoli/nx_spatial/src/f3ea4a2617c4c8b5aec4955a718e6ff1fc4d4e29?at=default).  Looks like he wrote a script related to finding [flow directions](https://bitbucket.org/gallipoli/nx_spatial/src/f3ea4a2617c4c8b5aec4955a718e6ff1fc4d4e29/nx_spatial/algorithms/flow_errors.py?at=default&fileviewer=file-view-default). Might be worth checking out.

**Comment by jesselangdon** [comment]
I think I've found a way to find stream segments (i.e. graph edges) with an incorrect flow direction.

https://github.com/SouthForkResearch/pyGNAT/commit/d2a358fc74d0aa22f89fdf10851d808f9057d8ba
