### ISSUE TITLE
Find flipped reaches

### ISSUE THREAD

**Issue by jesselangdon** [SouthForkResearch/pyGNAT#31]
pyGNAT should be able to detect stream reaches within a network with geometry that is incorrectly flowing upstream.

**Comment by MattReimer** [comment]
This one I think you can use NetworkX for exclusively. Look for any edges that share start and end but have different directions.

**Comment by jesselangdon** [comment]
I actually already have a function written for this.  Just added an issue for tracking purposes.

**Comment by jesselangdon** [comment]
Added a function for finding flipped edges.  It only finds the 'first' flipped edge (relative to adjacent non-flipped edges), but it's a start!

https://github.com/SouthForkResearch/pyGNAT/commit/8d25dd303767236a44f1bb1f74994707e6649416
